// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/ArmRaiseCommand.h"

ArmRaiseCommand::ArmRaiseCommand(Arm* m_arm)
:m_arm(m_arm){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ArmRaiseCommand");
    AddRequirements(m_arm);
}

// Called just before this Command runs the first time
void ArmRaiseCommand::Initialize() {
   m_arm->ArmRaise();
}

// Called repeatedly when this Command is scheduled to run
void ArmRaiseCommand::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool ArmRaiseCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ArmRaiseCommand::End(bool interrupted) {
    m_arm->ArmStop();
}

bool ArmRaiseCommand::RunsWhenDisabled() const {
    return false;
}