// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.
#include "commands/AutonomousCommand.h"

#include <wpi/raw_ostream.h> // for wpi outs()

AutonomousCommand::AutonomousCommand(Drive* m_drive, Arm* m_arm, Shooter* m_shooter)
:m_drive(m_drive),
m_arm(m_arm),
m_shooter(m_shooter)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("AutonomousCommand");
    AddRequirements(m_drive);
    AddRequirements(m_arm);
    AddRequirements(m_shooter);
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
    // do nothing
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
    // do nothing
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void AutonomousCommand::End(bool interrupted) {
    // do nothing
}

bool AutonomousCommand::RunsWhenDisabled() const {
    return false;
}